### ISSUE TITLE
Error while displaying the history in cli 

### ISSUE THREAD

**Issue by ranjansingh119** [NiteshOswal/SentimentAnalyzerService#2]
C:\Users\prince\Documents\Github\SentimentAnalyzerService\cli\history.js:19
                console.log((k+1) + ".\t" + [temp[0].replace(/-/g, " "), temp[1].replace(".dump", "")].join("\t"))
                                                                                ^

TypeError: Cannot read property 'replace' of undefined
    at C:\Users\prince\Documents\Github\SentimentAnalyzerService\cli\history.js:19:81
    at Array.forEach (native)
    at C:\Users\prince\Documents\Github\SentimentAnalyzerService\cli\history.js:16:18
    at C:\Users\prince\Documents\Github\SentimentAnalyzerService\lib\history.js:19:13
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by NiteshOswal** [comment]
We changed the format for dumps being stored, you have to flush it all!
